version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.1

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          mapping: |
            hivesim-rs/.* hivesim-rs-ci true
            simulators/portal/.* rust-ci true
          base-revision: origin/master
